version: '3.8'

services:
  signally_app:
    build: 
      context: .
      dockerfile: devops/docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development